import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "react-hot-toast"
import "./globals.css";
import Sidebar from "./components/Sidebar";
import Topbar from "./components/Topbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<body>
<div className="flex h-screen">
<Sidebar />
<div className="flex-1 flex flex-col">
<Topbar />
<main className="p-6 overflow-auto">{children}
          <Toaster position="top-right" />
</main>
</div>
</div>
</body>
    </html>
  );
}
